robot_base_frame: $(arg prefix)base_footprint
transform_tolerance: 0.2 #0.4
update_frequency: 5.0 #5.0 # set the frequency of the control
publish_frequency: 1.0 #1.0
obstacle_range: 2.5 #3.0
#mark_threshold: 1
publish_voxel_map: true
navigation_map:
  map_topic: /map
obstacles:
  observation_sources: b_scan_marking b_scan_clearing f_scan_marking f_scan_clearing
  b_scan_marking:
    topic: b_scan_rep117
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  b_scan_clearing:
    topic: b_scan_rep117
    data_type: LaserScan
    clearing: true
    marking: false
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  f_scan_marking:
    topic: f_scan_rep117
    data_type: LaserScan
    clearing: false
    marking: true
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25
  f_scan_clearing:
    topic: f_scan_rep117
    data_type: LaserScan
    clearing: true
    marking: false
    inf_is_valid: false
    min_obstacle_height: 0.13
    max_obstacle_height: 0.25

